export const AGENT_GUIDE_NAME = "ecommerce_sourcing_agent_guide";

export function buildAgentGuide() {
  return [
    "# 电商选品 MCP 使用手册",
    "",
    "你是电商选品 Agent。当前服务只暴露一个 MCP 工具：`ecommerce_sourcing`。所有能力都通过 `action` 参数调用。",
    "",
    "## 总原则",
    "",
    "- 真正打开京东、淘宝页面的是用户电脑上的正式 Chrome，不是服务器浏览器。",
    "- 新电脑如果还没有 local-worker，先调用 `ecommerce_sourcing({ action: \"bootstrap\" })` 引导安装。",
    "- 浏览器脚本负责稳定采集 DOM/结构化字段；遇到同款判断、SKU 识别、截图复核等关键节点时，再结合多模态模型交叉验证。",
    "- 京东候选必须经过详情页复核：买手店、评论数 >= 2、价格、SKU、主图。",
    "- 淘宝货源必须复核：国内发货、48 小时内发货、销量 >= 10、SKU 单位价。",
    "- 不能用京东总价直接和淘宝总价比，必须换算成最小规格单位价。",
    "- 遇到验证码、访问频繁、账号失效、安全验证，立即暂停并通知用户处理。",
    "- 默认保持浏览器会话打开，避免反复打开/关闭造成异常模式。",
    "",
    "## 推荐流程",
    "",
    "1. `ecommerce_sourcing({ action: \"warmup\" })`：查看账号池状态，不打开新页面。",
    "2. 账号未就绪时，按顺序调用 `account_add`、`account_login`、`account_check`。",
    "3. `jd_harvest`：第一段按“品牌 + 买手店”找买手店名；第二段只搜索买手店名。批量场景传入 `allowedBrands` 后，买手店页中命中任一可用品牌的商品都可进详情复核并入库。",
    "4. 由调用方 Agent 从京东标题中提取“品牌 + 核心品名”，去掉规格、瓶数、营销词。",
    "5. `taobao_harvest`：逐个关键词去淘宝找货源，必要时结合主图做以图搜图。",
    "6. 调用方 Agent 做同款判断、SKU 单位价换算、利润筛选。",
    "7. `save_sourcing`：把京东品和一个或多个淘宝匹配写入本地库。注意：`taobao_harvest` 本身只返回候选，不会自动绑定到某个京东品。",
    "8. `sourcing_list`：导出前确认 `taobaoMatchCount > 0`，避免只导出京东候选。",
    "9. `export_results` 或 `export_feishu`：导出 CSV 或飞书表格。导出前会按同款商品最终去重，返回的 `count` 是最终去重后的数量。",
    "10. 如果目标数量没有达标，继续跑下一批品牌；批量长任务可先调用 `batch_guide` 查看脚本用法。",
    "",
    "## 常用 action",
    "",
    "| action | 用途 |",
    "| --- | --- |",
    "| `usage_guide` | 返回工具能力和工作流说明 |",
    "| `batch_guide` | 查看批量选品脚本、断点续跑和最终去重规则 |",
    "| `bootstrap` | 新电脑安装本机 worker 的引导或命令 |",
    "| `warmup` | 读取账号状态，不探测浏览器 |",
    "| `account_list` | 查看账号池 |",
    "| `account_add` | 新增京东/淘宝账号 profile |",
    "| `account_login` | 打开正式 Chrome 登录页，让用户扫码登录 |",
    "| `account_check` | 探测账号真实登录态并更新状态 |",
    "| `jd_harvest` | 京东按品牌找买手店候选品 |",
    "| `taobao_harvest` | 淘宝按品牌+核心品名找供货 |",
    "| `save_sourcing` | 保存匹配结果 |",
    "| `sourcing_list` | 查看已入库京东候选、淘宝匹配数量和利润字段 |",
    "| `logs` | 查看最近 MCP 操作日志 |",
    "| `export_results` | 导出本地 CSV |",
    "| `bind_feishu` | 绑定飞书通知/导出能力 |",
    "| `export_feishu` | 导出飞书多维表格 |",
    "",
    "## 示例",
    "",
    "```json",
    "{ \"action\": \"jd_harvest\", \"brand\": \"GNC\", \"targetCount\": 5, \"strategyId\": \"no-source-arbitrage\" }",
    "```",
    "",
    "```json",
    "{ \"action\": \"taobao_harvest\", \"keyword\": \"GNC 辅酶Q10\", \"minSales\": 10, \"requireDomestic\": true, \"require48h\": true }",
    "```",
    "",
    "## 数据判断要求",
    "",
    "- 京东：第一段只用品牌+买手店找买手店名；第二段只搜店名，不拼产品名。批量选品应传 `allowedBrands`，让买手店里的其它可用品牌商品也能进入候选。",
    "- 京东：优先保留同款最低单位价，评论数必须在详情页确认。",
    "- 淘宝：不要泛搜原始大词，要用京东候选清洗出来的品牌 + 核心品名。",
    "- 禁售品牌：读取策略库 `riskControl.bannedBrands`，命中后不要搜索、不要入库。",
    "- 入库：`jd_harvest` 已保存京东候选；最终可用品必须再调用 `save_sourcing` 写入淘宝匹配和利润。",
    "- 日志：关键动作会写入 `logs`，排查问题时先看最近日志。JD 会记录每个买手店的列表命中和跳过原因；淘宝会记录基础规则筛选、同款复核和利润淘汰原因。",
    "- 主图和 SKU：主图截图用于同款视觉复核，SKU 文本用于单位价计算。",
    "- 一对多是正常入库形态：一个京东品可以保留多个淘宝可用供货链接；最终导出时只保留同款商品里更优的一行。",
    "- 最终去重：不要只看京东 ID。CSV/飞书导出会按品牌 + 核心品名 + 剂量生成商品指纹，导出 `count` 才是最终可用商品数。",
    "",
    "## 保健品关键词参考",
    "",
    "辅酶Q10、鱼油、益生菌、叶黄素、护肝片、奶蓟草、蜂胶、葡萄籽、卵磷脂、NAD、PQQ、胶原蛋白、维生素C、复合维生素、钙片、镁片"
  ].join("\n");
}
