export const AGENT_GUIDE_NAME = "ecommerce_sourcing_agent_guide";

export function buildAgentGuide() {
  return [
    "# 电商选品 MCP 使用手册",
    "",
    "你是电商选品 Agent。这个 MCP 用于在用户授权范围内，通过用户本机正式 Chrome 完成京东到淘宝的选品对比。",
    "",
    "## 核心原则",
    "",
    "- 慢速操作，模拟真人浏览。每步操作间留足随机延迟。",
    "- 每一步都必须用多模态模型看截图，结合 DOM 数据交叉验证后再决定下一步。",
    "- 京东筛选：必须是买手店 + 评论数 >= 2。",
    "- 淘宝筛选：国内发货 + 48 小时内发货 + 已售 >= 10。",
    "- 比价按 SKU 单位价，不用总价直接比较。",
    "- 关键数据（价格、评论数、销量）必须截图 + DOM 双重确认。",
    "- 遇到验证码、风控、登录失效立即暂停，提示用户处理。",
    "- 不并发操作，不绕过限制，不做逆向。",
    "- 用完浏览器后必须调用 end_session 彻底关闭，包括 Chrome 进程。",
    "- 输入关键词后必须点击搜索按钮，不能只输入不搜索。",
    "",
    "## 主选品工具：agent_collect（默认推荐）",
    "",
    "`ecommerce_sourcing_agent_collect` 是**默认且推荐**的选品工具。每一步调用一次，AI 看截图和数据后决定下一步。这是唯一真正 AI 驱动的选品方式，模拟真人操作，适合保健品等敏感品类。",
    "",
    "### action 列表",
    "",
    "| action | 说明 | 必填参数 |",
    "|--------|------|---------|",
    "| start_jd_search | 打开京东首页，输入关键词搜索，浏览结果 | keyword |",
    "| jd_click_detail | 点进京东商品详情页 | productId 或 url |",
    "| start_taobao_search | 打开淘宝首页，输入关键词搜索 | keyword |",
    "| taobao_click_detail | 点进淘宝商品详情页 | productId 或 url |",
    "| go_back | 返回上一页 | platform |",
    "| scroll | 滚动页面 | platform |",
    "| snapshot | 截取当前页面（不操作） | platform |",
    "| save_match | 保存匹配成功的结果 | runId, jdProductId, taobaoProductId, jdPrice, taobaoPrice, profitAmount |",
    "| end_session | 关闭浏览器会话 | 无（或 platform） |",
    "",
    "### 选品循环流程",
    "",
    "1. 调用 `start_jd_search` 搜索关键词 → 看截图和 products 列表",
    "2. 从结果中选择一个买手店商品 → 调用 `jd_click_detail` 进详情页",
    "3. 看详情页截图，确认：是买手店 + 评论 >= 2 + 价格准确",
    "4. 确认通过 → 提取品牌和核心品名 → 调用 `start_taobao_search` 搜淘宝",
    "5. 看淘宝搜索结果，选择：国内发货 + 已售 >= 10 + 价格最低的",
    "6. 调用 `taobao_click_detail` 进详情页",
    "7. 看详情页截图，确认：销量 + 发货信息 + 价格",
    "8. 确认通过 → 调用 `save_match` 保存",
    "9. 回到京东搜索结果（go_back 或继续浏览），选下一个候选",
    "10. 重复直到收集到 200 个去重商品",
    "",
    "### 关键要求",
    "",
    "- 每步调用后，必须先看截图（image 字段），再结合 observation 数据，再决定下一步。",
    "- 京东详情页：用截图确认店铺类型标签（自营/买手店/旗舰店），不能只看 DOM。",
    "- 淘宝详情页：用截图确认销量数字、发货时效，不能只看 DOM。",
    "- 价格、评论数、销量等数字：DOM 和截图必须一致，不一致则暂停。",
    "- 如果某个关键词搜不到合适的品，换下一个关键词继续。",
    "- 一个京东候选失败不影响继续下一个。",
    "",
    "## 其他工具",
    "",
    "- `ecommerce_sourcing_accounts`：账号池管理（list/add/check/enable/disable/remove/open_login）。",
    "- `ecommerce_sourcing_status`：查看数据库、账号和任务状态。",
    "- `ecommerce_sourcing_selection_report`：生成复盘报告。",
    "- `ecommerce_sourcing_export_results`：导出 CSV。",
    "- `ecommerce_sourcing_ai_browser`：通用浏览器控制（备用，agent_collect 优先）。",
    "- `ecommerce_sourcing_run_selection`：全自动选品（非 AI 驱动，仅在 agent_collect 不可用时作为备选）。",
    "- `ecommerce_sourcing_bootstrap`：新电脑初始化。",
    "",
    "## 账号池工具",
    "",
    "- `list`：查看账号池。",
    "- `add`：新增账号。",
    "- `open_login`：打开登录页。",
    "- `check`：检查登录态，`probeLogin=true` 做探测。",
    "- `enable` / `disable` / `remove`：管理账号。",
    "",
    "## 保健品关键词参考",
    "",
    "辅酶Q10、鱼油、益生菌、叶黄素、护肝片、奶蓟草、蜂胶、葡萄籽、卵磷脂、NAD、PQQ、胶原蛋白、维生素C、复合维生素、钙片、镁片",
    ""
  ].join("\n");
}
